"""Initial migration with all tables

Revision ID: 8e3d844d1f03
Revises: 
Create Date: 2025-08-04 14:22:30.734925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e3d844d1f03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_category', sa.String(), nullable=False),
    sa.Column('sensitivity_level', sa.String(), nullable=False),
    sa.Column('patient_identifier_id', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_identifier_id'], ['patient_identifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('data_embeddings_idx_1'), table_name='data_data_embeddings')
    op.drop_table('data_data_embeddings')
    op.alter_column('collections', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_collections_vector_db_id'), table_name='collections')
    op.alter_column('documents', 'document_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('documents_embedding_idx'), table_name='documents', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_documents_collection_id'), table_name='documents')
    op.drop_index(op.f('idx_documents_document_type'), table_name='documents')
    op.drop_index(op.f('idx_documents_facility_id'), table_name='documents')
    op.drop_index(op.f('idx_documents_patient_code'), table_name='documents')
    op.drop_index(op.f('idx_documents_patient_identifier_id'), table_name='documents')
    op.drop_column('documents', 'embedding')
    op.drop_column('documents', 'sensitivity_level')
    op.drop_column('documents', 'document_category')
    op.drop_column('documents', 'content')
    op.alter_column('facilities', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_facilities_name'), table_name='facilities')
    op.drop_index(op.f('idx_patient_identifiers_facility_id'), table_name='patient_identifiers')
    op.drop_index(op.f('idx_patient_identifiers_patient_code'), table_name='patient_identifiers')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_patient_identifiers_patient_code'), 'patient_identifiers', ['patient_code'], unique=False)
    op.create_index(op.f('idx_patient_identifiers_facility_id'), 'patient_identifiers', ['facility_id'], unique=False)
    op.create_index(op.f('idx_facilities_name'), 'facilities', ['name'], unique=False)
    op.alter_column('facilities', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('document_category', sa.VARCHAR(length=100), server_default=sa.text("'clinical'::character varying"), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('sensitivity_level', sa.VARCHAR(length=50), server_default=sa.text("'standard'::character varying"), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_documents_patient_identifier_id'), 'documents', ['patient_identifier_id'], unique=False)
    op.create_index(op.f('idx_documents_patient_code'), 'documents', ['patient_code'], unique=False)
    op.create_index(op.f('idx_documents_facility_id'), 'documents', ['facility_id'], unique=False)
    op.create_index(op.f('idx_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('idx_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_index(op.f('documents_embedding_idx'), 'documents', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('documents', 'document_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_collections_vector_db_id'), 'collections', ['vector_db_id'], unique=False)
    op.alter_column('collections', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('data_data_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_data_embeddings_pkey'))
    )
    op.create_index(op.f('data_embeddings_idx_1'), 'data_data_embeddings', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.drop_table('medical_documents')
    # ### end Alembic commands ###
