"""fix_patient_identifier_relationships

Revision ID: ce00cffd83bb
Revises: 8e3d844d1f03
Create Date: 2025-08-04 22:53:03.700185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce00cffd83bb'
down_revision: Union[str, Sequence[str], None] = '8e3d844d1f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('data_embeddings_embedding_idx'), table_name='data_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('data_embeddings')
    op.drop_index(op.f('data_embeddings_idx_1'), table_name='data_data_embeddings')
    op.drop_table('data_data_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_data_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_data_embeddings_pkey'))
    )
    op.create_index(op.f('data_embeddings_idx_1'), 'data_data_embeddings', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_table('data_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_embeddings_pkey'))
    )
    op.create_index(op.f('data_embeddings_embedding_idx'), 'data_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
